module.exports = async (req, res) => {
  try {
    const { email, password } = req.body;

    // Get user object from the database by email address
    const user = await usersDB.getUserByEmailAddress(email);

    // Compare the hash generated by request passwod and compare to the database hash
    const isValidPassord = compareHash(password, user.password);

    if (!isValidPassord) {
      res.statusMessage = 'Please enter valid credentials!';
      return res.status(400).end();
    }

    return res.status(201).json(user);
  } catch (err) {
    return res.status(400).json(err);
  }
};
