const jwt = require('jsonwebtoken');

const { usersDB } = require('../../database/queries/users');
const { compareHash } = require('../../helpers/auth/auth.helper');
const { config } = require('../../config');

module.exports = async (req, res) => {
  try {
    const { email, password } = req.body;

    // Get user object from the database by email address
    const user = await usersDB.getUserByEmailAddress(email);

    // Compare the hash generated by request passwod and compare to the database hash
    const isValidPassord = compareHash(password, user.password);

    if (!isValidPassord) {
      res.statusMessage = 'Please enter valid credentials!';
      return res.status(400).end();
    }

    // If the password is valid, sign the token, then pass it in the response along with user data
    // const currentUser = { userID: user.id, email: user.email };
    const currentUser = { userID: user.id };
    const jwtSecret = config.JWT_SECRET;
    const jwtExpiration = { expiresIn: '1 days' };

    const token = await jwt.sign(currentUser, jwtSecret, jwtExpiration);

    res.status(200).json({ token, userID: user.id });
  } catch (err) {
    throw new Error(err);
  }
};
